// Helper utility for realistic Hinglish customer reviews & randomized review counts (20-60)

export interface ReviewItem {
  id: string;
  name: string;
  userName?: string;
  location: string;
  outfit: string;
  productName?: string;
  rating: number;
  date: string;
  comment: string;
  verified: boolean;
  verifiedPurchase?: boolean;
  likes?: number;
  sizePurchased?: string;
  imageUrl?: string;
  photoUrl?: string;
  adminReply?: string;
}

/**
 * Generates a stable deterministic review count between 20 and 60 for any product ID.
 */
export const getProductReviewCount = (productId: string | number): number => {
  const str = String(productId || '');
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  // Yields a stable number between 20 and 60 inclusive
  const count = 20 + (Math.abs(hash) % 41);
  return count;
};

// 55+ Distinct, Realistic, High-Trust Indian Customer Reviews for Homepage in Natural Hinglish
export const HOMEPAGE_HINGLISH_REVIEWS: ReviewItem[] = [
  {
    id: 'hp-rev-1',
    name: 'Pooja Sharma',
    userName: 'Pooja Sharma',
    location: 'Artisan, Rajasthan',
    outfit: 'Floral Printed Cambric Suit Set',
    productName: 'Floral Printed Cambric Suit Set',
    rating: 5,
    date: '18 Feb 2026',
    comment: 'Kapde ki quality and finish ekdum lajawab hai! Pure cotton cambric fabric hai, garmi me pehnne ke liye super comfortable. Kota doria dupatta lightweight hai aur express delivery 3 din me ho gayi.',
    verified: true,
    verifiedPurchase: true,
    likes: 28,
  },
  {
    id: 'hp-rev-2',
    name: 'Divya Agarwal',
    userName: 'Divya Agarwal',
    location: 'Delhi NCR',
    outfit: 'Chanderi Silk Zardozi Anarkali',
    productName: 'Chanderi Silk Zardozi Anarkali',
    rating: 5,
    date: '16 Feb 2026',
    comment: 'Anarkali ka ghera aur fitting ekdum perfect aayi! Sizing chart ke hisab se M size liya tha, koi alteration ki jarurat nahi padi. Family function me sabne pucha kahan se order kiya.',
    verified: true,
    verifiedPurchase: true,
    likes: 34,
  },
  {
    id: 'hp-rev-3',
    name: 'Ruchika Joshi',
    userName: 'Ruchika Joshi',
    location: 'Ahmedabad, Gujarat',
    outfit: 'Chikankari Embroidered Cotton Kurti',
    productName: 'Chikankari Embroidered Cotton Kurti',
    rating: 4.5,
    date: '15 Feb 2026',
    comment: 'Fabric bohot hi soft hai aur chikankari embroidery work bohot neat hai. Pehle online boutique order karne me thoda doubt tha par real item dekh kar dil khush ho gaya.',
    verified: true,
    verifiedPurchase: true,
    likes: 19,
  },
  {
    id: 'hp-rev-4',
    name: 'Swati Verma',
    userName: 'Swati Verma',
    location: 'Lucknow, Uttar Pradesh',
    outfit: 'Banarasi Brocade Silk Suit Set',
    productName: 'Banarasi Brocade Silk Suit Set',
    rating: 5,
    date: '14 Feb 2026',
    comment: 'Suit aur dupatta dono bohot hi rich aur premium lagte hain. Color bilkul waisa hi hai jaisa site par photo me dikhaya tha. Packaging bhi kaafi royal thi!',
    verified: true,
    verifiedPurchase: true,
    likes: 22,
  },
  {
    id: 'hp-rev-5',
    name: 'Niharika Rao',
    userName: 'Niharika Rao',
    location: 'Bengaluru, Karnataka',
    outfit: 'Gota Patti Georgette Anarkali',
    productName: 'Gota Patti Georgette Anarkali',
    rating: 4,
    date: '12 Feb 2026',
    comment: 'Fitting L size ki bilkul exact hai. Gota patti ka kaam andar se chubhta nahi hai, inner lining soft hai. Online Razorpay se payment easily ho gaya aur tracking SMS mil gaya tha.',
    verified: true,
    verifiedPurchase: true,
    likes: 17,
  },
  {
    id: 'hp-rev-6',
    name: 'Harpreet Kaur',
    userName: 'Harpreet Kaur',
    location: 'Ludhiana, Punjab',
    outfit: 'Mulmul Cotton Printed Suit Set',
    productName: 'Mulmul Cotton Printed Suit Set',
    rating: 5,
    date: '11 Feb 2026',
    comment: 'Daily office wear ke liye perfect outfit hai. First wash ke baad bhi fabric shrink nahi hua aur color bhi nahi nikla. Very happy with Suit Aura Girls!',
    verified: true,
    verifiedPurchase: true,
    likes: 26,
  },
  {
    id: 'hp-rev-7',
    name: 'Priyanka Das',
    userName: 'Priyanka Das',
    location: 'Kolkata, West Bengal',
    outfit: 'Organza Silk Printed Suit',
    productName: 'Organza Silk Printed Suit',
    rating: 4.5,
    date: '09 Feb 2026',
    comment: 'Organza dupatta ka drape bohot graceful lagta hai. Suit me double interlock stitching ki hui hai jo generally online clothes me nahi milti. Definitely buying again!',
    verified: true,
    verifiedPurchase: true,
    likes: 23,
  },
  {
    id: 'hp-rev-8',
    name: 'Sunita Choudhary',
    userName: 'Sunita Choudhary',
    location: 'Jodhpur, Rajasthan',
    outfit: 'Handblock Printed Bandhani Suit',
    productName: 'Handblock Printed Bandhani Suit',
    rating: 5,
    date: '08 Feb 2026',
    comment: 'Authentic Heritage handblock feel hai. Cotton quality 10/10 hai aur pant me side pocket bhi hai jo bohot convenient lagti hai. Worth every rupee!',
    verified: true,
    verifiedPurchase: true,
    likes: 31,
  },
  {
    id: 'hp-rev-9',
    name: 'Komal Aggarwal',
    userName: 'Komal Aggarwal',
    location: 'Chandigarh',
    outfit: 'Velvet Festive Embroidered Suit',
    productName: 'Velvet Festive Embroidered Suit',
    rating: 5,
    date: '06 Feb 2026',
    comment: 'Winter wedding function ke liye lia tha, itna sundar look aaya ki sabhi relative tareef kar rahe the. Fabric rich and warm feel deta hai.',
    verified: true,
    verifiedPurchase: true,
    likes: 37,
  },
  {
    id: 'hp-rev-10',
    name: 'Shweta Singh',
    userName: 'Shweta Singh',
    location: 'Varanasi, Uttar Pradesh',
    outfit: 'Silk Blend Straight Kurta Set',
    productName: 'Silk Blend Straight Kurta Set',
    rating: 4,
    date: '05 Feb 2026',
    comment: 'Simple, sober aur classy suit. Neckline par metallic embroidery bohot elegant lagti hai. Size S ekdum true to size chart aaya.',
    verified: true,
    verifiedPurchase: true,
    likes: 15,
  },
  {
    id: 'hp-rev-11',
    name: 'Archana Tripathi',
    userName: 'Archana Tripathi',
    location: 'Indore, Madhya Pradesh',
    outfit: 'Chanderi Silk Flared Anarkali Set',
    productName: 'Chanderi Silk Flared Anarkali Set',
    rating: 5,
    date: '03 Feb 2026',
    comment: 'Fabric skin par bohot soft touch karta hai. Color aur finish exact picture jaisi aayi. WhatsApp par tracking details mil gayi thi, delivery fast thi!',
    verified: true,
    verifiedPurchase: true,
    likes: 21,
  },
  {
    id: 'hp-rev-12',
    name: 'Sakshi Jain',
    userName: 'Sakshi Jain',
    location: 'Surat, Gujarat',
    outfit: 'Printed Cotton Co-ord Suit Set',
    productName: 'Printed Cotton Co-ord Suit Set',
    rating: 5,
    date: '02 Feb 2026',
    comment: 'Co-ord set ka modern style aur Heritage block print combo killer lagta hai. Trouser me elastic comfortable hai. Highly satisfied with Suit Aura Girls!',
    verified: true,
    verifiedPurchase: true,
    likes: 29,
  },
  {
    id: 'hp-rev-13',
    name: 'Meenakshi Sundaram',
    userName: 'Meenakshi Sundaram',
    location: 'Chennai, Tamil Nadu',
    outfit: 'Royal Silk Kali Anarkali Set',
    productName: 'Royal Silk Kali Anarkali Set',
    rating: 4.5,
    date: '31 Jan 2026',
    comment: 'Anarkali ka ghera bohot hi shaandar hai. Fabric ka luster natural hai aur dupatta drape karna ekdum easy. Family puja me sabne tareef ki.',
    verified: true,
    verifiedPurchase: true,
    likes: 25,
  },
  {
    id: 'hp-rev-14',
    name: 'Ritu Bhardwaj',
    userName: 'Ritu Bhardwaj',
    location: 'Gurgaon, Haryana',
    outfit: 'Angrakha Style Cotton Suit Set',
    productName: 'Angrakha Style Cotton Suit Set',
    rating: 5,
    date: '30 Jan 2026',
    comment: 'Angrakha cut ka tassel detailing super cute lagta hai. M size bilkul accurate hai. Delivery box me handmade fragrance potpourri bhi thi, great boutique touch!',
    verified: true,
    verifiedPurchase: true,
    likes: 32,
  },
  {
    id: 'hp-rev-15',
    name: 'Kavya Nair',
    userName: 'Kavya Nair',
    location: 'Kochi, Kerala',
    outfit: 'Mirror Work Sharara Set',
    productName: 'Mirror Work Sharara Set',
    rating: 5,
    date: '28 Jan 2026',
    comment: 'Sharara set ki fitting aur mirror embroidery mindblowing hai. Real mirror work hai, plastic nahi hai. Night wedding functions ke liye 100% recommended!',
    verified: true,
    verifiedPurchase: true,
    likes: 38,
  },
  {
    id: 'hp-rev-16',
    name: 'Shilpa Deshmukh',
    userName: 'Shilpa Deshmukh',
    location: 'Pune, Maharashtra',
    outfit: 'Sanganeri Print Straight Suit',
    productName: 'Sanganeri Print Straight Suit',
    rating: 4,
    date: '27 Jan 2026',
    comment: 'Traditional Sanganeri block print ekdum authentic lagta hai. Cotton fabric breathable hai. Office hours me poora din comfort rehta hai.',
    verified: true,
    verifiedPurchase: true,
    likes: 18,
  },
  {
    id: 'hp-rev-17',
    name: 'Nidhi Singhal',
    userName: 'Nidhi Singhal',
    location: 'Noida, Uttar Pradesh',
    outfit: 'Gota Border Kota Doria Suit',
    productName: 'Gota Border Kota Doria Suit',
    rating: 5,
    date: '25 Jan 2026',
    comment: 'Kota doria dupatta ka feel bohot airy hai. Gota patti borders neatly stitched hain. Pristine condition me safe packaging ke saath deliver hua.',
    verified: true,
    verifiedPurchase: true,
    likes: 27,
  },
  {
    id: 'hp-rev-18',
    name: 'Pooja Bhatia',
    userName: 'Pooja Bhatia',
    location: 'Amritsar, Punjab',
    outfit: 'Hand Embroidered Chanderi Kurti',
    productName: 'Hand Embroidered Chanderi Kurti',
    rating: 4.5,
    date: '24 Jan 2026',
    comment: 'Neckline par threadwork bohot hi intricate hai. Inner cotton lining bohot breathable hai so garmi nahi lagti. Sizing exact hai.',
    verified: true,
    verifiedPurchase: true,
    likes: 20,
  },
  {
    id: 'hp-rev-19',
    name: 'Bhawna Trivedi',
    userName: 'Bhawna Trivedi',
    location: 'Udaipur, Rajasthan',
    outfit: 'Bandhej Print Palazzo Suit',
    productName: 'Bandhej Print Palazzo Suit',
    rating: 5,
    date: '22 Jan 2026',
    comment: 'Pure Bandhej Heritage colors! Palazzo me pocket bhi hai jo mobile rakhne ke liye super handy hai. Pehli baar me hi favorite ho gaya.',
    verified: true,
    verifiedPurchase: true,
    likes: 30,
  },
  {
    id: 'hp-rev-20',
    name: 'Simran Kaur',
    userName: 'Simran Kaur',
    location: 'Patiala, Punjab',
    outfit: 'Tissue Silk Designer Anarkali',
    productName: 'Tissue Silk Designer Anarkali',
    rating: 5,
    date: '20 Jan 2026',
    comment: 'Tissue silk sheen bohot hi subtle and classy lagti hai. Marriage reception me pehna tha, sabhi friend ne link mangwaya.',
    verified: true,
    verifiedPurchase: true,
    likes: 35,
  },
  {
    id: 'hp-rev-21',
    name: 'Deepa Menon',
    userName: 'Deepa Menon',
    location: 'Trivandrum, Kerala',
    outfit: 'Cotton Modal Straight Suit Set',
    productName: 'Cotton Modal Straight Suit Set',
    rating: 4,
    date: '19 Jan 2026',
    comment: 'Modal cotton fabric super smooth lagta hai skin par. Wash ke baad koi shrinkage nahi aayi. Worth every rupee.',
    verified: true,
    verifiedPurchase: true,
    likes: 16,
  },
  {
    id: 'hp-rev-22',
    name: 'Rekha Malhotra',
    userName: 'Rekha Malhotra',
    location: 'Dehradun, Uttarakhand',
    outfit: 'Kashmiri Threadwork Suit Set',
    productName: 'Kashmiri Threadwork Suit Set',
    rating: 5,
    date: '17 Jan 2026',
    comment: 'Resham threadwork embroidery bohot hi delicate aur rich lagti hai. Fabric quality luxury boutique level ki hai.',
    verified: true,
    verifiedPurchase: true,
    likes: 29,
  },
  {
    id: 'hp-rev-23',
    name: 'Aarti Saxena',
    userName: 'Aarti Saxena',
    location: 'Bhopal, Madhya Pradesh',
    outfit: 'Heritage Dabu Print Cotton Suit',
    productName: 'Heritage Dabu Print Cotton Suit',
    rating: 4.5,
    date: '15 Jan 2026',
    comment: 'Dabu print handcrafted feel deta hai. Dupatta wide aur long hai. Fitting me 2-inch inner margin bhi hai for future adjustment.',
    verified: true,
    verifiedPurchase: true,
    likes: 24,
  },
  {
    id: 'hp-rev-24',
    name: 'Ishita Gupta',
    userName: 'Ishita Gupta',
    location: 'Kanpur, Uttar Pradesh',
    outfit: 'Organza Floral Printed Anarkali',
    productName: 'Organza Floral Printed Anarkali',
    rating: 5,
    date: '14 Jan 2026',
    comment: 'Floral print ki vibrancy mindblowing hai. Organza dupatta billowy lagta hai. UPI payment par ₹150 discount bhi mil gaya tha.',
    verified: true,
    verifiedPurchase: true,
    likes: 31,
  },
  {
    id: 'hp-rev-25',
    name: 'Muskan Chawla',
    userName: 'Muskan Chawla',
    location: 'Jammu',
    outfit: 'Heavy Velvet Zardozi Sharara',
    productName: 'Heavy Velvet Zardozi Sharara',
    rating: 5,
    date: '12 Jan 2026',
    comment: 'Velvet fabric me rich sheen hai. Zardozi embroidery back side se chubhti nahi hai. Highly impressed with Suit Aura Girls craftsmanship!',
    verified: true,
    verifiedPurchase: true,
    likes: 36,
  },
  {
    id: 'hp-rev-26',
    name: 'Tanvi Kulkarni',
    userName: 'Tanvi Kulkarni',
    location: 'Nagpur, Maharashtra',
    outfit: 'Cotton Flex Block Print Suit',
    productName: 'Cotton Flex Block Print Suit',
    rating: 4,
    date: '10 Jan 2026',
    comment: 'Cotton flex fabric wrinkle-resistant hai. Office wear ke liye bohot hi neat look deta hai. Sizing chart perfect hai.',
    verified: true,
    verifiedPurchase: true,
    likes: 19,
  },
  {
    id: 'hp-rev-27',
    name: 'Radhika Merchant',
    userName: 'Radhika Merchant',
    location: 'Mumbai, Maharashtra',
    outfit: 'Georgette Foil Print Kali Kurti',
    productName: 'Georgette Foil Print Kali Kurti',
    rating: 5,
    date: '08 Jan 2026',
    comment: 'Foil print washed water me nahi nikla. Flared kali pattern me movement bohot graceful lagti hai. Top class service!',
    verified: true,
    verifiedPurchase: true,
    likes: 33,
  },
  {
    id: 'hp-rev-28',
    name: 'Sneha Reddy',
    userName: 'Sneha Reddy',
    location: 'Hyderabad, Telangana',
    outfit: 'Chanderi Zari Border Kurta Set',
    productName: 'Chanderi Zari Border Kurta Set',
    rating: 4.5,
    date: '07 Jan 2026',
    comment: 'Zari border work subtle aur sophisticated hai. Saree se hatkar kuch ethnic try karna tha, ye best decision raha!',
    verified: true,
    verifiedPurchase: true,
    likes: 22,
  },
  {
    id: 'hp-rev-29',
    name: 'Vandana Pillai',
    userName: 'Vandana Pillai',
    location: 'Coimbatore, Tamil Nadu',
    outfit: 'Pure Cotton Handblock Anarkali',
    productName: 'Pure Cotton Handblock Anarkali',
    rating: 5,
    date: '05 Jan 2026',
    comment: '100% pure cotton breathable material. Stitching double interlocked hai. Parcel 3 days me South India tak deliver ho gaya.',
    verified: true,
    verifiedPurchase: true,
    likes: 27,
  },
  {
    id: 'hp-rev-30',
    name: 'Meera Rajput',
    userName: 'Meera Rajput',
    location: 'Kota, Rajasthan',
    outfit: 'Kota Doria Silk Printed Suit',
    productName: 'Kota Doria Silk Printed Suit',
    rating: 5,
    date: '03 Jan 2026',
    comment: 'Kota doria weave authentic Rajasthan ka feel deta hai. Lightweight and easy to drape. My 3rd suit from SAG!',
    verified: true,
    verifiedPurchase: true,
    likes: 28,
  },
  {
    id: 'hp-rev-31',
    name: 'Pallavi Sharma',
    userName: 'Pallavi Sharma',
    location: 'Patna, Bihar',
    outfit: 'Embroidered Rayon Slub Set',
    productName: 'Embroidered Rayon Slub Set',
    rating: 4,
    date: '01 Jan 2026',
    comment: 'Rayon slub fabric falls nicely. Embroidery neat hai. Overall fitting L size ki ekdum fit aayi.',
    verified: true,
    verifiedPurchase: true,
    likes: 17,
  },
  {
    id: 'hp-rev-32',
    name: 'Chhavi Rastogi',
    userName: 'Chhavi Rastogi',
    location: 'Meerut, Uttar Pradesh',
    outfit: 'Lucknowi Chikankari Georgette Suit',
    productName: 'Lucknowi Chikankari Georgette Suit',
    rating: 5,
    date: '29 Dec 2025',
    comment: 'Georgette Chikankari shadow work bohot hi ethereal lagta hai. Cotton inner lining pehle se stiched hai so no hassle!',
    verified: true,
    verifiedPurchase: true,
    likes: 31,
  },
  {
    id: 'hp-rev-33',
    name: 'Payal Bhasin',
    userName: 'Payal Bhasin',
    location: 'Faridabad, Haryana',
    outfit: 'Jacquard Weave Silk Kurta Set',
    productName: 'Jacquard Weave Silk Kurta Set',
    rating: 4.5,
    date: '27 Dec 2025',
    comment: 'Jacquard weave fabric high end feel deta hai. Festival and dinner outing ke liye ideal outfit hai.',
    verified: true,
    verifiedPurchase: true,
    likes: 21,
  },
  {
    id: 'hp-rev-34',
    name: 'Jyoti Pandey',
    userName: 'Jyoti Pandey',
    location: 'Ranchi, Jharkhand',
    outfit: 'Printed Cotton Mulmul Sharara',
    productName: 'Printed Cotton Mulmul Sharara',
    rating: 5,
    date: '25 Dec 2025',
    comment: 'Mulmul cotton ka softness unbelievable hai. Sharara ghera comfortable hai, bilkul heavy lagne nahi deta.',
    verified: true,
    verifiedPurchase: true,
    likes: 26,
  },
  {
    id: 'hp-rev-35',
    name: 'Shruthi Iyer',
    userName: 'Shruthi Iyer',
    location: 'Thane, Maharashtra',
    outfit: 'Bandhani Georgette Dupatta Set',
    productName: 'Bandhani Georgette Dupatta Set',
    rating: 5,
    date: '23 Dec 2025',
    comment: 'Dupatta Bandhani print super bright and festive hai. WhatsApp support par sizing confirm karne ke baad order kiya tha, exact size aaya.',
    verified: true,
    verifiedPurchase: true,
    likes: 29,
  },
  {
    id: 'hp-rev-36',
    name: 'Neha Khandelwal',
    userName: 'Neha Khandelwal',
    location: 'Ajmer, Rajasthan',
    outfit: 'Handblock Printed Cambric Set',
    productName: 'Handblock Printed Cambric Set',
    rating: 4,
    date: '21 Dec 2025',
    comment: 'Authentic Heritage motifs! Pant waistband elastic super comfortable hai, stomach par mark nahi chodta.',
    verified: true,
    verifiedPurchase: true,
    likes: 18,
  },
  {
    id: 'hp-rev-37',
    name: 'Kriti Sanon',
    userName: 'Kriti Sanon',
    location: 'Raipur, Chhattisgarh',
    outfit: 'Chanderi Foil Work Flared Kurti',
    productName: 'Chanderi Foil Work Flared Kurti',
    rating: 5,
    date: '19 Dec 2025',
    comment: 'Chanderi fabric luster classy hai. Sizing M size perfect fitting with inner margins.',
    verified: true,
    verifiedPurchase: true,
    likes: 25,
  },
  {
    id: 'hp-rev-38',
    name: 'Sonali Bendre',
    userName: 'Sonali Bendre',
    location: 'Nashik, Maharashtra',
    outfit: 'Gota Patti Cambric Anarkali',
    productName: 'Gota Patti Cambric Anarkali',
    rating: 5,
    date: '17 Dec 2025',
    comment: 'Anarkali flared look photo se bhi zyaada pretty hai. Packing gift box me aayi thi. Highly satisfied!',
    verified: true,
    verifiedPurchase: true,
    likes: 30,
  },
  {
    id: 'hp-rev-39',
    name: 'Garima Sethi',
    userName: 'Garima Sethi',
    location: 'Shimla, Himachal Pradesh',
    outfit: 'Velvet Heavily Embroidered Suit',
    productName: 'Velvet Heavily Embroidered Suit',
    rating: 4.5,
    date: '15 Dec 2025',
    comment: 'Cold winter weather me velvet suit super cozy and warm tha. Golden zari work is top tier.',
    verified: true,
    verifiedPurchase: true,
    likes: 24,
  },
  {
    id: 'hp-rev-40',
    name: 'Preeti Goyal',
    userName: 'Preeti Goyal',
    location: 'Gwalior, Madhya Pradesh',
    outfit: 'Cotton Cambric Angrakha Set',
    productName: 'Cotton Cambric Angrakha Set',
    rating: 5,
    date: '13 Dec 2025',
    comment: 'Angrakha neckline with latkan details looks ultra stylish! Cotton quality is solid.',
    verified: true,
    verifiedPurchase: true,
    likes: 27,
  },
  {
    id: 'hp-rev-41',
    name: 'Richa Jha',
    userName: 'Richa Jha',
    location: 'Dhanbad, Jharkhand',
    outfit: 'Silk Blend Embroidered Straight Suit',
    productName: 'Silk Blend Embroidered Straight Suit',
    rating: 4,
    date: '11 Dec 2025',
    comment: 'Classy color combination. Sleeves finishing clean hai. Value for money.',
    verified: true,
    verifiedPurchase: true,
    likes: 16,
  },
  {
    id: 'hp-rev-42',
    name: 'Ankita Lokhande',
    userName: 'Ankita Lokhande',
    location: 'Jalandhar, Punjab',
    outfit: 'Georgette Sharara Set with Dupatta',
    productName: 'Georgette Sharara Set with Dupatta',
    rating: 5,
    date: '09 Dec 2025',
    comment: 'Sharara ka ghera bohot hi bada aur shaandar hai! Sangeet night par dance karne ke liye ekdum mast outfit hai. Fabric feel bohot soft hai.',
    verified: true,
    verifiedPurchase: true,
    likes: 32,
  },
  {
    id: 'hp-rev-43',
    name: 'Mansi Joshi',
    userName: 'Mansi Joshi',
    location: 'Vadodara, Gujarat',
    outfit: 'Pure Cotton Co-ord Loungewear',
    productName: 'Pure Cotton Co-ord Loungewear',
    rating: 5,
    date: '07 Dec 2025',
    comment: 'Comfort level 100! Travel and casual outing ke liye best suit set. Pant pocket is super practical.',
    verified: true,
    verifiedPurchase: true,
    likes: 23,
  },
  {
    id: 'hp-rev-44',
    name: 'Parul Patel',
    userName: 'Parul Patel',
    location: 'Rajkot, Gujarat',
    outfit: 'Bandhani Printed Cotton Anarkali',
    productName: 'Bandhani Printed Cotton Anarkali',
    rating: 4.5,
    date: '05 Dec 2025',
    comment: 'Bandhani print contrast dupatta with flared anarkali looks so traditional yet modern.',
    verified: true,
    verifiedPurchase: true,
    likes: 28,
  },
  {
    id: 'hp-rev-45',
    name: 'Upasana Kamineni',
    userName: 'Upasana Kamineni',
    location: 'Vijayawada, Andhra Pradesh',
    outfit: 'Banarasi Silk Blend Festive Kurti',
    productName: 'Banarasi Silk Blend Festive Kurti',
    rating: 5,
    date: '03 Dec 2025',
    comment: 'Royal silk feel without being heavy or itchy. Delivered in pristine condition.',
    verified: true,
    verifiedPurchase: true,
    likes: 29,
  },
  {
    id: 'hp-rev-46',
    name: 'Barkha Dutt',
    userName: 'Barkha Dutt',
    location: 'Srinagar, Jammu & Kashmir',
    outfit: 'Kashmiri Aari Work Silk Suit',
    productName: 'Kashmiri Aari Work Silk Suit',
    rating: 5,
    date: '01 Dec 2025',
    comment: 'Aari needlework is clean and authentic. Color combination is royal. Highly recommended boutique!',
    verified: true,
    verifiedPurchase: true,
    likes: 35,
  },
  {
    id: 'hp-rev-47',
    name: 'Surbhi Chandna',
    userName: 'Surbhi Chandna',
    location: 'Delhi NCR',
    outfit: 'Organza Floral Sharara Suit',
    productName: 'Organza Floral Sharara Suit',
    rating: 4.5,
    date: '29 Nov 2025',
    comment: 'Drape of organza dupatta is super aesthetic for Instagram photos! Received 40+ DMs asking for link.',
    verified: true,
    verifiedPurchase: true,
    likes: 31,
  },
  {
    id: 'hp-rev-48',
    name: 'Dimple Kapadia',
    userName: 'Dimple Kapadia',
    location: 'Mumbai, Maharashtra',
    outfit: 'Chanderi Zardozi Yoke Anarkali',
    productName: 'Chanderi Zardozi Yoke Anarkali',
    rating: 5,
    date: '27 Nov 2025',
    comment: 'Graceful Yoke design with intricate gold thread embroidery. Tailored fit is exquisite.',
    verified: true,
    verifiedPurchase: true,
    likes: 33,
  },
  {
    id: 'hp-rev-49',
    name: 'Reena Kapoor',
    userName: 'Reena Kapoor',
    location: 'Agra, Uttar Pradesh',
    outfit: 'Handblock Printed Cotton Dupatta Set',
    productName: 'Handblock Printed Cotton Dupatta Set',
    rating: 4,
    date: '25 Nov 2025',
    comment: 'Breathable cotton fabric with authentic Heritage block print smell. Very comfortable.',
    verified: true,
    verifiedPurchase: true,
    likes: 18,
  },
  {
    id: 'hp-rev-50',
    name: 'Smriti Irani',
    userName: 'Smriti Irani',
    location: 'Ghaziabad, Uttar Pradesh',
    outfit: 'Mulmul Cotton Straight Kurta Set',
    productName: 'Mulmul Cotton Straight Kurta Set',
    rating: 5,
    date: '23 Nov 2025',
    comment: 'Mulmul cotton feels like feather on skin. Perfect for long summer days. 10/10 quality.',
    verified: true,
    verifiedPurchase: true,
    likes: 27,
  },
  {
    id: 'hp-rev-51',
    name: 'Tanya Mittal',
    userName: 'Tanya Mittal',
    location: 'Chandigarh',
    outfit: 'Gota Patti Work Chanderi Suit',
    productName: 'Gota Patti Work Chanderi Suit',
    rating: 5,
    date: '21 Nov 2025',
    comment: 'Chiffon dupatta par gold gota border detailing se poora look hi royal ho jata hai. Fitting ekdum mindblowing aayi!',
    verified: true,
    verifiedPurchase: true,
    likes: 26,
  },
  {
    id: 'hp-rev-52',
    name: 'Kavita Singhania',
    userName: 'Kavita Singhania',
    location: 'Artisan, Rajasthan',
    outfit: 'Sanganeri Print Cambric Anarkali',
    productName: 'Sanganeri Print Cambric Anarkali',
    rating: 4.5,
    date: '19 Nov 2025',
    comment: 'Flared anarkali with original Sanganeri floral motifs. Authentic craftsmanship at reasonable price.',
    verified: true,
    verifiedPurchase: true,
    likes: 24,
  },
  {
    id: 'hp-rev-53',
    name: 'Shreya Saxena',
    userName: 'Shreya Saxena',
    location: 'Bareilly, Uttar Pradesh',
    outfit: 'Rayon Slub Embroidered Kurti Set',
    productName: 'Rayon Slub Embroidered Kurti Set',
    rating: 4,
    date: '17 Nov 2025',
    comment: 'Good fabric weight, smooth texture, true to size M fit. Quick response from customer team on WhatsApp.',
    verified: true,
    verifiedPurchase: true,
    likes: 17,
  },
  {
    id: 'hp-rev-54',
    name: 'Tanvi Joshi',
    userName: 'Tanvi Joshi',
    location: 'Solapur, Maharashtra',
    outfit: 'Pure Silk Kali Festive Suit',
    productName: 'Pure Silk Kali Festive Suit',
    rating: 5,
    date: '15 Nov 2025',
    comment: 'Kali pattern gives rich ethnic flair. Wore for Laxmi Puja, felt so traditional and graceful.',
    verified: true,
    verifiedPurchase: true,
    likes: 30,
  },
  {
    id: 'hp-rev-55',
    name: 'Rhea Kapoor',
    userName: 'Rhea Kapoor',
    location: 'Gurgaon, Haryana',
    outfit: 'Cotton Flex Embroidered Co-ord Set',
    productName: 'Cotton Flex Embroidered Co-ord Set',
    rating: 5,
    date: '13 Nov 2025',
    comment: 'Modern cut, ethnic handblock prints, and sturdy pockets in pants. What more can one ask for? Superb!',
    verified: true,
    verifiedPurchase: true,
    likes: 31,
  }
];


const INDIAN_BUYER_NAMES = [
  'Ananya Sharma', 'Meenakshi Sundaram', 'Ritu Bhardwaj', 'Kavya Nair', 'Shilpa Deshmukh',
  'Nidhi Singhal', 'Pooja Bhatia', 'Bhawna Trivedi', 'Divya Agarwal', 'Ruchika Joshi',
  'Swati Verma', 'Niharika Rao', 'Harpreet Kaur', 'Priyanka Das', 'Sunita Choudhary',
  'Komal Aggarwal', 'Shweta Singh', 'Archana Tripathi', 'Simran Kaur', 'Deepa Menon',
  'Rekha Malhotra', 'Aarti Saxena', 'Sakshi Jain', 'Ishita Gupta', 'Muskan Chawla',
  'Tanvi Kulkarni', 'Radhika Merchant', 'Sneha Reddy', 'Vandana Pillai', 'Meera Rajput',
  'Pallavi Sharma', 'Chhavi Rastogi', 'Payal Bhasin', 'Jyoti Pandey', 'Shruthi Iyer',
  'Neha Khandelwal', 'Kriti Sanon', 'Sonali Bendre', 'Garima Sethi', 'Preeti Goyal',
  'Richa Jha', 'Ankita Lokhande', 'Mansi Joshi', 'Parul Patel', 'Upasana Kamineni',
  'Barkha Dutt', 'Surbhi Chandna', 'Dimple Kapadia', 'Reena Kapoor', 'Smriti Irani'
];

const INDIAN_LOCATIONS = [
  'Artisan, Rajasthan', 'Delhi NCR', 'Bengaluru, Karnataka', 'Mumbai, Maharashtra',
  'Pune, Maharashtra', 'Chandigarh', 'Ludhiana, Punjab', 'Indore, Madhya Pradesh',
  'Ahmedabad, Gujarat', 'Lucknow, Uttar Pradesh', 'Kolkata, West Bengal', 'Jodhpur, Rajasthan',
  'Varanasi, Uttar Pradesh', 'Surat, Gujarat', 'Hyderabad, Telangana', 'Patna, Bihar',
  'Nagpur, Maharashtra', 'Noida, Uttar Pradesh', 'Gurgaon, Haryana', 'Dehradun, Uttarakhand',
  'Udaipur, Rajasthan', 'Amritsar, Punjab', 'Bhopal, Madhya Pradesh', 'Kochi, Kerala',
  'Vadodara, Gujarat', 'Ranchi, Jharkhand', 'Jammu', 'Shimla, Himachal Pradesh',
  'Coimbatore, Tamil Nadu', 'Raipur, Chhattisgarh'
];

const SIZES = ['S', 'M', 'L', 'XL', 'XXL'];

const RECENT_DATES = [
  '18 Feb 2026', '15 Feb 2026', '12 Feb 2026', '09 Feb 2026', '06 Feb 2026',
  '03 Feb 2026', '31 Jan 2026', '28 Jan 2026', '25 Jan 2026', '22 Jan 2026',
  '19 Jan 2026', '16 Jan 2026', '13 Jan 2026', '10 Jan 2026', '07 Jan 2026',
  '04 Jan 2026', '01 Jan 2026', '29 Dec 2025', '26 Dec 2025', '23 Dec 2025',
  '20 Dec 2025', '17 Dec 2025', '14 Dec 2025', '11 Dec 2025', '08 Dec 2025',
  '05 Dec 2025', '02 Dec 2025', '29 Nov 2025', '26 Nov 2025', '23 Nov 2025'
];

/**
 * Returns product-tailored Hinglish reviews for Product Detail Page (PDP).
 * Generates EXACTLY `targetCount` unique, realistic reviews matching the product's reviewCount.
 */
export const getProductSpecificHinglishReviews = (product: any, targetCount?: number): ReviewItem[] => {
  if (!product) return HOMEPAGE_HINGLISH_REVIEWS.slice(0, 5);

  const name = product.name || 'Suit Set';
  const category = product.category || 'Suits';
  const fabric = product.fabric || 'Pure Cotton';
  const idStr = String(product.id || '0');

  // Determine exact count needed
  const totalNeeded = targetCount && targetCount > 0 
    ? targetCount 
    : (product.reviewCount || getProductReviewCount(product.id));

  const templates = [
    `Sachi me bohot hi pyara outfit hai! "${name}" ka fabric (${fabric}) touch me ekdum soft aur breathable hai. Fitting M size ki bilkul boutique tailoring jaisi aayi.`,
    `Color photo se bhi zyaada bright aur beautiful lagta hai real me. Dupatta drape karna bohot easy hai aur pant me inner margin bhi diya hua hai. Packaging 10/10!`,
    `Mummy ke liye birthday gift lia tha "${name}", unko bohot pasand aaya! Order karne ke 3 din me express delivery ho gayi aur online payment safe tha.`,
    `Stitching and embroidery finishing bohot clean hai. Wash ke baad bhi fabric ka softness aur color bilkul fade nahi hua. Value for money purchase!`,
    `Ghera (flair) aur fitting dono bohot hi royal lagte hain! Marriage function me pehna tha aur sabhi relatives ne compliment kiya. Truly authentic Heritage craft!`,
    `Neckline design aur border detailing bohot hi classy hain. Pehnne me koi discomfort nahi hota. Suit Aura Girls ka material hamesha top class rehta hai.`,
    `Pehli baar order kiya tha, thoda hesitancy thi online boutique buying me par real item dekh kar saare doubt khatam ho gaye. Superb fabric and fitting!`,
    `Garmi me poore din pehne ke baad bhi bilkul sweat feel nahi hua. Fabric super breathable hai. 100% recommended for daily & office wear!`,
    `Pant me side pocket bhi hai jo bohot useful hai mobile aur keys rakhne ke liye. Overall fitting ekdum exact aayi hai sizing chart ke hisab se.`,
    `Dupatta ka length aur width bohot generous hai, chota nahi hai bilkul. Drape karne par bohot graceful look aata hai.`,
    `Fabric ki thickness standard hai, light me transparent nahi hota. Lining quality bhi soft cotton ki lagi hai.`,
    `First wash me halke se cold water me wash kiya, koi color bleed nahi hua. Heritage print bilkul intact hai.`,
    `Sizing chart ke hisab se L size liya tha, bilkul perfect fitting. Waist aur bust area me bilkul tight feel nahi hota.`,
    `Festive celebration ke liye order kiya tha, matching juttis ke saath wear kiya. Sabne pucha kahan se shopping ki!`,
    `Delivery speed bohot impressive thi. Courier boy ne box parcel properly handle karke deliver kiya.`,
    `Embroidery thread work piche se chubhta nahi hai. Inner finishing clean interlock stitching ke saath hai.`,
    `Boutique se stitching karwane me hi ₹1200 lag jaate hain, yahan ready-to-wear itne kam price me mil gaya. Great deal!`,
    `Bandhani/Handblock motifs ekdum crisp aur traditional hain. Real handloom artisan work lagta hai.`,
    `Product ka fabric weight light hai par look bohot rich aur heavy lagta hai. Marriage and puja events ke liye best option.`,
    `Size XL mangwaya tha, fitting super comfortable hai. Sleeves and shoulder cut accurate hai.`,
    `SAG ki customer support team via WhatsApp bohot helpful hai. Tracking info turant mil gayi thi.`,
    `Quality Amazon aur Flipkart ke regular sellers se 100 times better hai. Proper luxury boutique outfit!`,
    `Wash karne ke baad bhi colors bilkul vibrant rehte hain. Cotton fabric ki quality sachi me top-notch hai.`,
    `Kurta length 46 inches hai jo tall height par bhi bohot elegant dikhta hai. High recommendation!`,
    `Gota patti borders are neatly stitched without any loose threads. Quality check perfect lagta hai.`,
    `Poora set pehn kar picture post ki thi Instagram par, 50+ DMs aaye asking for link!`,
    `Fabric skin par bilkul soft touch karta hai, koi irritation nahi hoti. Handloom cotton feel hai.`,
    `Side seams me extra 2-inch margin hai so future me size adjustment easily ho sakta hai.`,
    `Delivery super fast thi! Sirf 3 din me parcel branded box me safe deliver ho gaya.`,
    `Sober aur classy look hai! Koi faltu extra bling nahi hai, ekdum royal elegance feel hota hai.`,
    `Pant elastic is firm yet stretchable. Knees par stretch dene me uncomfortable nahi lagta.`,
    `Suit Aura Girls se ye mera 2nd suit hai! Har ek dress ekdum masterpiece aati hai.`,
    `Neckline ki embroidery se suit ka poora grace badh jata hai. Simple chain ke saath mast lagta hai.`,
    `True Heritage craftsmanship! Authentic block print smell and pure cotton comfort.`,
    `Value for money! Same quality offline stores me 4000+ me milti hai.`
  ];

  const reviews: ReviewItem[] = [];

  for (let i = 0; i < totalNeeded; i++) {
    const nameIdx = (i + Number(idStr.replace(/[^0-9]/g, '') || 1)) % INDIAN_BUYER_NAMES.length;
    const locIdx = (i * 3 + Number(idStr.replace(/[^0-9]/g, '') || 1)) % INDIAN_LOCATIONS.length;
    const sizeIdx = (i + 1) % SIZES.length;
    const dateIdx = i % RECENT_DATES.length;
    const tplIdx = i % templates.length;

    // Rating: 90% 5-star, 10% 4-star for realistic customer feedback balance
    const rating = (i % 7 === 6) ? 4 : 5;
    const likes = 5 + ((i * 7 + 3) % 28);

    reviews.push({
      id: `pdp-rev-${i + 1}-${idStr}`,
      name: INDIAN_BUYER_NAMES[nameIdx],
      userName: INDIAN_BUYER_NAMES[nameIdx],
      location: INDIAN_LOCATIONS[locIdx],
      outfit: name,
      productName: name,
      rating,
      date: RECENT_DATES[dateIdx],
      comment: templates[tplIdx],
      verified: true,
      verifiedPurchase: true,
      sizePurchased: SIZES[sizeIdx],
      likes,
    });
  }

  return reviews;
};

